// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.14.0
// source: proto/bank.proto

package bank_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BankOperationClient is the client API for BankOperation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BankOperationClient interface {
	// Sends a greeting
	DoBankOp(ctx context.Context, in *BankRequest, opts ...grpc.CallOption) (*BankReply, error)
}

type bankOperationClient struct {
	cc grpc.ClientConnInterface
}

func NewBankOperationClient(cc grpc.ClientConnInterface) BankOperationClient {
	return &bankOperationClient{cc}
}

func (c *bankOperationClient) DoBankOp(ctx context.Context, in *BankRequest, opts ...grpc.CallOption) (*BankReply, error) {
	out := new(BankReply)
	err := c.cc.Invoke(ctx, "/bank.BankOperation/DoBankOp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BankOperationServer is the server API for BankOperation service.
// All implementations must embed UnimplementedBankOperationServer
// for forward compatibility
type BankOperationServer interface {
	// Sends a greeting
	DoBankOp(context.Context, *BankRequest) (*BankReply, error)
	mustEmbedUnimplementedBankOperationServer()
}

// UnimplementedBankOperationServer must be embedded to have forward compatible implementations.
type UnimplementedBankOperationServer struct {
}

func (UnimplementedBankOperationServer) DoBankOp(context.Context, *BankRequest) (*BankReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoBankOp not implemented")
}
func (UnimplementedBankOperationServer) mustEmbedUnimplementedBankOperationServer() {}

// UnsafeBankOperationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BankOperationServer will
// result in compilation errors.
type UnsafeBankOperationServer interface {
	mustEmbedUnimplementedBankOperationServer()
}

func RegisterBankOperationServer(s grpc.ServiceRegistrar, srv BankOperationServer) {
	s.RegisterService(&BankOperation_ServiceDesc, srv)
}

func _BankOperation_DoBankOp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankOperationServer).DoBankOp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bank.BankOperation/DoBankOp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankOperationServer).DoBankOp(ctx, req.(*BankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BankOperation_ServiceDesc is the grpc.ServiceDesc for BankOperation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BankOperation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bank.BankOperation",
	HandlerType: (*BankOperationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DoBankOp",
			Handler:    _BankOperation_DoBankOp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/bank.proto",
}
